baseURL = "http://localhost:1313"
languageCode = "en-us"
title = "Sajjad Momeni"
theme = "typo"

# Main menu configuration
[[menu.main]]
identifier = "home"
url = "/"
weight = 1

[[menu.main]]
identifier = "blogs"
url = "/blogs/"
weight = 2

[[menu.main]]
identifier = "posts"
url = "/posts/"
weight = 3

[[menu.main]]
identifier = "about"
url = "/about/"
weight = 4

[[menu.main]]
identifier = "library"
url = "/library/"
weight = 5

[params]
  defaultTheme = "dark"
  description = "A blog about Machine Learning and AI"
  menu = ["home", "blogs", "posts", "about", "library"]
  
  [params.menuNames]
    home = "home"
    blogs = "blogs"
    posts = "posts"
    about = "about"
    library = "library"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = false
    noClasses = true
    style = "monokai"

[taxonomies]
  category = "categories"
  tag = "tags"
