baseURL = '/'
languageCode = 'en-us'
defaultContentLanguage = 'en-us'
title = 'My Blog'
theme = 'typo'
relativeURLs = true
uglyURLs = false
canonifyURLs = false
absURL = false

[security]
  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', '^hugo$']
  [security.funcs]
    getenv = ['^HUGO_']
  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']

[module]
[module.hugoVersion]
extended = true
min = "0.92.0"

# Main menu configuration
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = -100
pre = "home"

[[menu.main]]
identifier = "about"
name = "About"
url = "/about"
weight = -90
pre = "user"

[[menu.main]]
identifier = "search"
name = "Search"
url = "/search"
weight = -80
pre = "search"

[params]
  env = "production"
  description = "My personal blog"
  keywords = ["blog", "personal", "technology"]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true

[params.breadcrumbs]
enabled = true
showCurrentPage = true
home = "Home"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = false
    noClasses = true
    style = "monokai"

[taxonomies]
  category = "categories"
  tag = "tags"

[outputs]
  home = ["HTML", "RSS", "JSON"]
